In [2]:
import numpy as np
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


In [8]:
#Q2
print(np.zeros((3,4)).astype(int))
print(np.ones((2,5)).astype(int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
#Q3
print(np.eye(5).astype(int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
#Q4
print(np.random.rand(10))

[0.96282345 0.90288756 0.66780353 0.62042474 0.72439034 0.87636182
 0.32277779 0.172675   0.43421665 0.36302721]


In [12]:
#Q5
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#Q6
arr=np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])

[20 30 40]


In [14]:
#Q7
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [15]:
#Q8
rand_arr = np.random.randint(1, 100, 10)

print("Random Array:", rand_arr)
print("Mean:", np.mean(rand_arr))
print("Median:", np.median(rand_arr))
print("Max:", np.max(rand_arr))
print("Min:", np.min(rand_arr))

Random Array: [44 70 73 31 99 52 35 99 29 62]
Mean: 59.4
Median: 57.0
Max: 99
Min: 29


In [16]:
#Q9
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

product = np.dot(mat1, mat2)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [17]:
#Q10
arr4 = np.array([5, 10, 15, 20, 25, 30])
greater_than_15 = arr4[arr4 > 15]

print("Elements greater than 15:", greater_than_15)

Elements greater than 15: [20 25 30]
